name: check_link_checker

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 12 * *"

jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      # This job must fail, as there are broken links
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'

      - name: Yay! The job has failed! It detected broken links put in on purpose!
        run: success()
        if: ${{ failure() }}
