name: check-link-checker

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 12 * *"

jobs:
  check-link-checker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      # This job must fail, as there are broken links
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
        continue-on-error: true

      - name: Yay! The job has failed! It detected broken links put in on purpose!
        run: exit 0
        if: ${{ failure() }}
        continue-on-error: true

      - name: No! The job should have failed! I broke mlc_config.json (and hence the checker) and this must make this script fail
        run: exit 1


